### ISSUE TITLE
Issue while reading quickReply/Predefined set of messages

### ISSUE THREAD

**Issue by MuhammedSwalih** [MyPureCloud/genesys-messenger-transport-mobile-sdk#191]
I can able to send & receive normal text messages, when I try to read some predefined set of messages from the server I am getting the following error in the iOS SDK version 2.4....   

(MMSDKTransportWebSocket) Failed to deserialize message
0   MessengerTransport                  0x102fcf657        kfun:kotlinx.serialization.json.internal#getJsonNameIndexOrThrow__at__kotlinx.serialization.descriptors.SerialDescriptor(kotlinx.serialization.json.Json;kotlin.String;kotlin.String){}kotlin.Int + 663

**Comment by AfanasievAnton** [comment]
@MuhammedSwalih 
Can you share with me an example of predefined set of messages that you are trying to send?

**Comment by MuhammedSwalih** [comment]
Sure @AfanasievAnton , here's a sample screenshot
![WhatsApp Image 2023-06-26 at 8 17 14 PM](https://github.com/MyPureCloud/genesys-messenger-transport-mobile-sdk/assets/9816228/b02dcfb0-50f4-478b-8509-6d1a25cf7b57)

**Comment by AfanasievAnton** [comment]
@MuhammedSwalih , Thanks for your fast reply. 

The Mobile Transport SDK does not currently support messages of "type":"Structured". We have plans to implement this feature later this year.

However, I want to confirm whether your application crashes when parsing such messages. In this case, it is expected that the parsing failure will be logged to the console, but no event or message will be dispatched. Can you confirm if this matches your experience?

**Comment by MuhammedSwalih** [comment]
@AfanasievAnton App is not crashing, only a serialization error is showing in the console. another issue I am facing is while fetching the chat history since the previous messages contain "Structured" messages I am not able to retrieve the chat

**Comment by AfanasievAnton** [comment]
@MuhammedSwalih Hmm... I can see why.  Given that this feature is not yet supported, it is recommended that applications avoid enabling quick replies,( aka Messages with type Structured). Anyway, I will promptly attend to the issue you raised, strengthening the resilience of the Transport SDK when handling unknown message types  and release a version with the fix.

**Comment by AfanasievAnton** [comment]
@MuhammedSwalih Can you try `v2.4.1` and tell me, if you are still seeing this behaviour?

**Comment by AfanasievAnton** [comment]
@MuhammedSwalih Thank you for your feedback.
